name: CI - Windows x64 MSVC 2

on:
  schedule:
    - cron: "15 9 * * 1-5"  # Weekday mornings at 09:15 UTC
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number || github.sha }}
  cancel-in-progress: true

jobs:
  windows_x64_msvc:
    runs-on: arc-runner-set
    env:
      BUILD_DIR: build-windows
    steps:
      - name: Add Bash to PATH
        run: |
          echo "Adding Bash to PATH"
          echo "C:\Program Files\Git\bin" >> $Env:GITHUB_PATH

      - name: Verify Bash is in PATH
        run: bash --version

      - name: "Checking out repository"
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: "Setting up Python"
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: "Installing Python packages"
        run: |
          bash pwd
          bash dir
          bash "
          python3 -m venv .venv &&
          source .venv/bin/activate &&
          python3 -m pip install -r iree/runtime/bindings/python/iree/runtime/build_requirements.txt
          "

      - name: "Installing requirements"
        run: |
          bash "
          choco install ccache --yes
          "

      - name: "Configuring MSVC"
        run: |
          bash '
          source <(ilammy/msvc-dev-cmd@v1.13.0 -c "echo" > /tmp/msvc.sh) &&
          source /tmp/msvc.sh
          '

      - name: "Building IREE"
        run: |
          bash "
          ./build_tools/cmake/build_all.sh ${BUILD_DIR}
          "

      - name: "Testing IREE"
        run: |
          bash "
          ./build_tools/cmake/ctest_all.sh ${BUILD_DIR}
          "
